export const FETCH_JOBS_START = 'FETCH_JOBS_START';
export const FETCH_JOBS_SUCCESS = 'FETCH_JOBS_SUCCESS';
export const FETCH_JOBS_FAIL = 'FETCH_JOBS_FAIL';
export const FETCH_JOB_DATA_START = 'FETCH_JOB_DATA_START';
export const FETCH_JOB_DATA_SUCCESS = 'FETCH_JOB_DATA_SUCCESS';
export const FETCH_JOB_DATA_FAIL = 'FETCH_JOB_DATA_FAIL';